#!/bin/sh
set -e
export LC_ALL=C

#scripts/fribidi-config
#scripts/fribidi-build $@
scripts/libass-config
scripts/libass-build $@
scripts/libacc-config
scripts/libacc-build $@
scripts/x264-config
scripts/x264-build $@
scripts/libvpx-config
scripts/libvpx-build $@
scripts/libopus-config
scripts/libopus-build $@
scripts/ffmpeg-config
scripts/ffmpeg-build $@
scripts/mpv-config
scripts/mpv-build $@
