#!/bin/sh
set -e
BUILD="$(pwd)"

OPTIONS="$@"

#if "$BUILD"/scripts/test-libmpv ; then
#    OPTIONS="$OPTIONS --with-pic"
#fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/libopus
# Later libacc doesn't automatically run configure with autogen.sh anymore
./configure --prefix="$BUILD/build_libs" --enable-static --disable-shared $OPTIONS


