#!/bin/sh
set -e
BUILD="$(pwd)"

OPTIONS="$@"

#if "$BUILD"/scripts/test-libmpv ; then
#    OPTIONS="$OPTIONS --with-pic"
#fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/libvpx
./configure --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm $OPTIONS
# ./configure --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" --enable-static --disable-shared $OPTIONS
# ./configure --prefix="$HOME/ffmpeg_build" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm
